CREATE TABLE `Information` (
	`CCCD` VARCHAR(255) NOT NULL UNIQUE,
	`Name` VARCHAR(255),
	`Gender` BOOLEAN,
	`BHYT` VARCHAR(255),
	`Phone` VARCHAR(255),
	`Job` VARCHAR(255),
	`Department` VARCHAR(255),
	`Address` VARCHAR(255),
	`Medical_History` LONGTEXT,
	`ID_Family` BIGINT,
	PRIMARY KEY(`CCCD`)
);


CREATE TABLE `Account` (
	`ID_Family` BIGINT NOT NULL UNIQUE,
	`PassWord` VARCHAR(255),
	`Email` VARCHAR(255),
	PRIMARY KEY(`ID_Family`)
);


CREATE TABLE `Receipt` (
	`ID_Receipt` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`ID_Patient` VARCHAR(255),
	`ID_Doctor` VARCHAR(255),
	`Place` VARCHAR(255),
	`Date` DATETIME,
	`Reason` LONGTEXT,
	`Diagnosis` VARCHAR(255),
	`Treat` VARCHAR(255),
	`Url_Result` VARCHAR(255),
	`Url_BillDrug` VARCHAR(255),
	`Remind` LONGTEXT,
	`Date_Visit` DATETIME,
	`Blood_Pressure` INTEGER,
	`Weight` INTEGER,
	`Height` INTEGER,
	`Heart_Rate` INTEGER,
	`Temperature` INTEGER,
	PRIMARY KEY(`ID_Receipt`)
);


CREATE TABLE `Family` (
	`ID_Family` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` TEXT(65535),
	PRIMARY KEY(`ID_Family`)
);


CREATE TABLE `Room_Detail` (
	`ID_Room` VARCHAR(255) NOT NULL UNIQUE,
	`ID_IsFollowed` VARCHAR(255) NOT NULL,
	`Status` BOOLEAN,
	PRIMARY KEY(`ID_Room`, `ID_IsFollowed`)
);


CREATE TABLE `Room` (
	`iD_Room` VARCHAR(255) NOT NULL UNIQUE,
	`PIN` VARCHAR(255),
	PRIMARY KEY(`iD_Room`)
);


ALTER TABLE `Receipt`
ADD FOREIGN KEY(`ID_Patient`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Receipt`
ADD FOREIGN KEY(`ID_Doctor`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Information`
ADD FOREIGN KEY(`ID_Family`) REFERENCES `Family`(`ID_Family`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Room_Detail`
ADD FOREIGN KEY(`ID_IsFollowed`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Room_Detail`
ADD FOREIGN KEY(`ID_Room`) REFERENCES `Room`(`iD_Room`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Account`
ADD FOREIGN KEY(`ID_Family`) REFERENCES `Family`(`ID_Family`)
ON UPDATE NO ACTION ON DELETE NO ACTION;