CREATE TABLE `Information` (
	`CCCD` VARCHAR(255) NOT NULL UNIQUE,
	`Name` VARCHAR(255),
	`Gender` BOOLEAN,
	`BHYT` VARCHAR(255),
	`Phone` VARCHAR(255),
	`Job` VARCHAR(255),
	`Department` VARCHAR(255),
	`Address` VARCHAR(255),
	`Medical_History` LONGTEXT,
	`ID_Family` BIGINT NOT NULL,
	PRIMARY KEY(`CCCD`)
);


CREATE TABLE `Drug` (
	`ID_Drug` VARCHAR(255) NOT NULL UNIQUE,
	`Name_Drug` VARCHAR(255),
	`Description` VARCHAR(255),
	`Price` DECIMAL,
	PRIMARY KEY(`ID_Drug`)
);


CREATE TABLE `Bill` (
	`ID_Bill` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Total` BIGINT,
	PRIMARY KEY(`ID_Bill`)
);


CREATE TABLE `Detail_Bill` (
	`ID_Bill` BIGINT NOT NULL UNIQUE,
	`ID_Drug` VARCHAR(255) NOT NULL,
	`Amount_Drug` INTEGER,
	PRIMARY KEY(`ID_Bill`, `ID_Drug`)
);


CREATE TABLE `Account` (
	`UserName` VARCHAR(255) NOT NULL UNIQUE,
	`PassWord` VARCHAR(255),
	`Email` VARCHAR(255),
	`Permission` BOOLEAN,
	PRIMARY KEY(`UserName`)
);


CREATE TABLE `Receipt` (
	`ID_Receipt` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`ID_Patient` VARCHAR(255),
	`ID_Doctor` VARCHAR(255),
	`Place` VARCHAR(255),
	`Date` DATETIME,
	`Reason` LONGTEXT,
	`Diagnosis` VARCHAR(255),
	`Treat` VARCHAR(255),
	`Url_Result` VARCHAR(255),
	`ID_Bill` BIGINT,
	`Remind` LONGTEXT,
	`Date_Visit` DATETIME,
	`Blood_Pressure` INTEGER,
	`Weight` INTEGER,
	`Height` INTEGER,
	`Heart_Rate` INTEGER,
	`Temperature` INTEGER,
	PRIMARY KEY(`ID_Receipt`)
);


CREATE TABLE `Family` (
	`ID_Family` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` TEXT(65535),
	PRIMARY KEY(`ID_Family`)
);


CREATE TABLE `Follow` (
	`ID_Follow` VARCHAR(255) NOT NULL UNIQUE,
	`ID_IsFollowed` VARCHAR(255) NOT NULL,
	`Is_delete` BOOLEAN,
	PRIMARY KEY(`ID_Follow`, `ID_IsFollowed`)
);


ALTER TABLE `Detail_Bill`
ADD FOREIGN KEY(`ID_Bill`) REFERENCES `Bill`(`ID_Bill`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Detail_Bill`
ADD FOREIGN KEY(`ID_Drug`) REFERENCES `Drug`(`ID_Drug`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Account`
ADD FOREIGN KEY(`UserName`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Receipt`
ADD FOREIGN KEY(`ID_Patient`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Receipt`
ADD FOREIGN KEY(`ID_Doctor`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Receipt`
ADD FOREIGN KEY(`ID_Bill`) REFERENCES `Bill`(`ID_Bill`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Information`
ADD FOREIGN KEY(`ID_Family`) REFERENCES `Family`(`ID_Family`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Follow`
ADD FOREIGN KEY(`ID_Follow`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Follow`
ADD FOREIGN KEY(`ID_IsFollowed`) REFERENCES `Information`(`CCCD`)
ON UPDATE NO ACTION ON DELETE NO ACTION;